/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Nat;
export const SubscriptionTier = IDL.Variant({
  'org' : IDL.Null,
  'pro' : IDL.Null,
  'creator' : IDL.Null,
  'admin' : IDL.Null,
  'free' : IDL.Null,
});
export const Collection = IDL.Record({
  'id' : IDL.Nat,
  'ownerId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'tier' : SubscriptionTier,
  'description' : IDL.Text,
  'maxSize' : IDL.Nat,
});
export const AuditEntry = IDL.Record({
  'action' : IDL.Text,
  'timestamp' : Timestamp,
  'details' : IDL.Opt(IDL.Text),
  'caller' : IDL.Principal,
});
export const NftStatus = IDL.Variant({
  'deleted' : IDL.Null,
  'active' : IDL.Null,
  'burned' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreatorId = IDL.Text;
export const RewardTier = IDL.Variant({
  'bronze' : IDL.Null,
  'gold' : IDL.Null,
  'none' : IDL.Null,
  'platinum' : IDL.Null,
  'silver' : IDL.Null,
});
export const Nft = IDL.Record({
  'id' : IDL.Nat,
  'status' : NftStatus,
  'title' : IDL.Text,
  'imageBlob' : ExternalBlob,
  'edition' : IDL.Text,
  'collectionId' : IDL.Opt(IDL.Nat),
  'ownerId' : IDL.Principal,
  'discountCode' : IDL.Opt(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'creatorId' : CreatorId,
  'businessName' : IDL.Opt(IDL.Text),
  'mintDate' : Timestamp,
  'description' : IDL.Text,
  'website' : IDL.Opt(IDL.Text),
  'auditHistory' : IDL.Vec(AuditEntry),
  'rewardTier' : RewardTier,
  'assetHash' : IDL.Text,
  'membershipId' : IDL.Opt(IDL.Text),
  'nftUniqueId' : IDL.Text,
});
export const PaymentProofStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PaymentProof = IDL.Record({
  'id' : IDL.Text,
  'status' : PaymentProofStatus,
  'principal' : IDL.Principal,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'submittedAt' : IDL.Int,
  'reviewedAt' : IDL.Opt(IDL.Int),
  'reviewedBy' : IDL.Opt(IDL.Principal),
  'txHash' : IDL.Text,
  'tierRequested' : IDL.Text,
  'networkType' : IDL.Text,
});
export const AlertType = IDL.Variant({
  'mint_confirmation' : IDL.Null,
  'draft_purge' : IDL.Null,
  'subscription_expiry' : IDL.Null,
  'transfer_window' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'creditsTotal' : IDL.Nat,
  'oisyWalletAddress' : IDL.Opt(IDL.Text),
  'emailAlerts' : IDL.Vec(AlertType),
  'maxSlots' : IDL.Nat,
  'createdAt' : Timestamp,
  'subscriptionTier' : SubscriptionTier,
  'creatorId' : CreatorId,
  'email' : IDL.Opt(IDL.Text),
  'stripeProductId' : IDL.Opt(IDL.Text),
  'activeSlots' : IDL.Nat,
  'creditsUsed' : IDL.Nat,
  'principalId' : IDL.Principal,
  'creditsResetAt' : Timestamp,
});
export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_6 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const Result_3 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Result_5 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const CollectionWithCount = IDL.Record({
  'id' : IDL.Nat,
  'ownerId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'tier' : SubscriptionTier,
  'description' : IDL.Text,
  'nftCount' : IDL.Nat,
  'maxSize' : IDL.Nat,
});
export const Result_4 = IDL.Variant({
  'ok' : IDL.Record({
    'id' : IDL.Nat,
    'tokenId' : IDL.Nat,
    'collectionId' : IDL.Opt(IDL.Nat),
    'nftUniqueId' : IDL.Text,
  }),
  'err' : IDL.Record({ 'message' : IDL.Text }),
});
export const TransferResult = IDL.Record({
  'newOwnerPrincipal' : IDL.Opt(IDL.Text),
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
});
export const UpdateMetadataRequest = IDL.Record({
  'discountCode' : IDL.Opt(IDL.Text),
  'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
  'businessName' : IDL.Opt(IDL.Text),
  'website' : IDL.Opt(IDL.Text),
  'rewardTier' : IDL.Opt(RewardTier),
  'membershipId' : IDL.Opt(IDL.Text),
});
export const VerifyResult = IDL.Record({
  'tokenId' : IDL.Nat,
  'edition' : IDL.Text,
  'collectionId' : IDL.Opt(IDL.Nat),
  'owner' : IDL.Principal,
  'discountCode' : IDL.Opt(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'creatorId' : CreatorId,
  'businessName' : IDL.Opt(IDL.Text),
  'network' : IDL.Text,
  'mintDate' : Timestamp,
  'website' : IDL.Opt(IDL.Text),
  'rewardTier' : RewardTier,
  'assetHash' : IDL.Text,
  'membershipId' : IDL.Opt(IDL.Text),
  'nftUniqueId' : IDL.Text,
  'canisterId' : IDL.Text,
});
export const Result_1 = IDL.Variant({
  'ok' : IDL.Vec(VerifyResult),
  'err' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : VerifyResult, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__adminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  '__collectionStore' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Collection))],
      ['query'],
    ),
  '__creatorIndex' : IDL.Func([], [IDL.Reserved], ['query']),
  '__globalAuditLog' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(AuditEntry)],
      ['query'],
    ),
  '__lastMintTime' : IDL.Func([], [IDL.Reserved], ['query']),
  '__mintCount' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextCollectionId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextNftId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nftStore' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Nft))],
      ['query'],
    ),
  '__paymentProofStore' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Text, PaymentProof))],
      ['query'],
    ),
  '__rateLimitStore' : IDL.Func([], [IDL.Reserved], ['query']),
  '__selfCanisterId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__stripeConfigStore' : IDL.Func([], [IDL.Reserved], ['query']),
  '__userStore' : IDL.Func(
      [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  '__verifiedEmails' : IDL.Func([], [IDL.Reserved], ['query']),
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_6], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'approvePaymentProof' : IDL.Func([IDL.Text], [Result_3], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'burnNft' : IDL.Func([IDL.Nat], [Result_2], []),
  'createCheckoutSession' : IDL.Func(
      [
        IDL.Vec(IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Nat })),
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'createCollection' : IDL.Func([IDL.Text, IDL.Text], [Result_5], []),
  'deleteCollection' : IDL.Func([IDL.Nat], [], []),
  'deleteNft' : IDL.Func([IDL.Nat], [Result_2], []),
  'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getCallerProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCanisterId' : IDL.Func([], [IDL.Text], ['query']),
  'getCollection' : IDL.Func([IDL.Nat], [IDL.Opt(Collection)], ['query']),
  'getCollectionId' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
  'getCreditsStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'used' : IDL.Nat,
          'remaining' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getMyPaymentProofs' : IDL.Func([], [IDL.Vec(PaymentProof)], ['query']),
  'getNft' : IDL.Func([IDL.Nat], [IDL.Opt(Nft)], ['query']),
  'getSlotsStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'used' : IDL.Nat,
          'remaining' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'status' : IDL.Text })],
      [],
    ),
  'getStripeStatus' : IDL.Func(
      [],
      [IDL.Record({ 'mode' : IDL.Text, 'configured' : IDL.Bool })],
      ['query'],
    ),
  'getTotalMinted' : IDL.Func([], [IDL.Nat], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listMyActiveNfts' : IDL.Func([], [IDL.Vec(Nft)], ['query']),
  'listMyCollections' : IDL.Func([], [IDL.Vec(CollectionWithCount)], ['query']),
  'listMyNfts' : IDL.Func([], [IDL.Vec(Nft)], ['query']),
  'listPaymentProofs' : IDL.Func([], [IDL.Vec(PaymentProof)], ['query']),
  'mintNft' : IDL.Func(
      [
        ExternalBlob,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [Result_4],
      [],
    ),
  'rejectPaymentProof' : IDL.Func([IDL.Text, IDL.Text], [Result_3], []),
  'saveCallerProfile' : IDL.Func([UserProfile], [], []),
  'sendVerificationEmail' : IDL.Func([IDL.Text], [], []),
  'setEmail' : IDL.Func([IDL.Text], [], []),
  'setEmailAlerts' : IDL.Func([IDL.Vec(AlertType)], [], []),
  'setOisyWalletAddress' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setUserStripeProductId' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [Result_2],
      [],
    ),
  'submitPaymentProof' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Result_3],
      [],
    ),
  'transferNft' : IDL.Func([IDL.Nat, IDL.Principal], [TransferResult], []),
  'updateBusinessMetadata' : IDL.Func(
      [IDL.Nat, UpdateMetadataRequest],
      [Result_2],
      [],
    ),
  'verifyNftByCreatorId' : IDL.Func([IDL.Text], [Result_1], ['query']),
  'verifyNftPublic' : IDL.Func([IDL.Text], [Result], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Nat;
  const SubscriptionTier = IDL.Variant({
    'org' : IDL.Null,
    'pro' : IDL.Null,
    'creator' : IDL.Null,
    'admin' : IDL.Null,
    'free' : IDL.Null,
  });
  const Collection = IDL.Record({
    'id' : IDL.Nat,
    'ownerId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'tier' : SubscriptionTier,
    'description' : IDL.Text,
    'maxSize' : IDL.Nat,
  });
  const AuditEntry = IDL.Record({
    'action' : IDL.Text,
    'timestamp' : Timestamp,
    'details' : IDL.Opt(IDL.Text),
    'caller' : IDL.Principal,
  });
  const NftStatus = IDL.Variant({
    'deleted' : IDL.Null,
    'active' : IDL.Null,
    'burned' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreatorId = IDL.Text;
  const RewardTier = IDL.Variant({
    'bronze' : IDL.Null,
    'gold' : IDL.Null,
    'none' : IDL.Null,
    'platinum' : IDL.Null,
    'silver' : IDL.Null,
  });
  const Nft = IDL.Record({
    'id' : IDL.Nat,
    'status' : NftStatus,
    'title' : IDL.Text,
    'imageBlob' : ExternalBlob,
    'edition' : IDL.Text,
    'collectionId' : IDL.Opt(IDL.Nat),
    'ownerId' : IDL.Principal,
    'discountCode' : IDL.Opt(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'creatorId' : CreatorId,
    'businessName' : IDL.Opt(IDL.Text),
    'mintDate' : Timestamp,
    'description' : IDL.Text,
    'website' : IDL.Opt(IDL.Text),
    'auditHistory' : IDL.Vec(AuditEntry),
    'rewardTier' : RewardTier,
    'assetHash' : IDL.Text,
    'membershipId' : IDL.Opt(IDL.Text),
    'nftUniqueId' : IDL.Text,
  });
  const PaymentProofStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PaymentProof = IDL.Record({
    'id' : IDL.Text,
    'status' : PaymentProofStatus,
    'principal' : IDL.Principal,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'submittedAt' : IDL.Int,
    'reviewedAt' : IDL.Opt(IDL.Int),
    'reviewedBy' : IDL.Opt(IDL.Principal),
    'txHash' : IDL.Text,
    'tierRequested' : IDL.Text,
    'networkType' : IDL.Text,
  });
  const AlertType = IDL.Variant({
    'mint_confirmation' : IDL.Null,
    'draft_purge' : IDL.Null,
    'subscription_expiry' : IDL.Null,
    'transfer_window' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'creditsTotal' : IDL.Nat,
    'oisyWalletAddress' : IDL.Opt(IDL.Text),
    'emailAlerts' : IDL.Vec(AlertType),
    'maxSlots' : IDL.Nat,
    'createdAt' : Timestamp,
    'subscriptionTier' : SubscriptionTier,
    'creatorId' : CreatorId,
    'email' : IDL.Opt(IDL.Text),
    'stripeProductId' : IDL.Opt(IDL.Text),
    'activeSlots' : IDL.Nat,
    'creditsUsed' : IDL.Nat,
    'principalId' : IDL.Principal,
    'creditsResetAt' : Timestamp,
  });
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_6 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const Result_3 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Result_5 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const CollectionWithCount = IDL.Record({
    'id' : IDL.Nat,
    'ownerId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'tier' : SubscriptionTier,
    'description' : IDL.Text,
    'nftCount' : IDL.Nat,
    'maxSize' : IDL.Nat,
  });
  const Result_4 = IDL.Variant({
    'ok' : IDL.Record({
      'id' : IDL.Nat,
      'tokenId' : IDL.Nat,
      'collectionId' : IDL.Opt(IDL.Nat),
      'nftUniqueId' : IDL.Text,
    }),
    'err' : IDL.Record({ 'message' : IDL.Text }),
  });
  const TransferResult = IDL.Record({
    'newOwnerPrincipal' : IDL.Opt(IDL.Text),
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
  });
  const UpdateMetadataRequest = IDL.Record({
    'discountCode' : IDL.Opt(IDL.Text),
    'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
    'businessName' : IDL.Opt(IDL.Text),
    'website' : IDL.Opt(IDL.Text),
    'rewardTier' : IDL.Opt(RewardTier),
    'membershipId' : IDL.Opt(IDL.Text),
  });
  const VerifyResult = IDL.Record({
    'tokenId' : IDL.Nat,
    'edition' : IDL.Text,
    'collectionId' : IDL.Opt(IDL.Nat),
    'owner' : IDL.Principal,
    'discountCode' : IDL.Opt(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'creatorId' : CreatorId,
    'businessName' : IDL.Opt(IDL.Text),
    'network' : IDL.Text,
    'mintDate' : Timestamp,
    'website' : IDL.Opt(IDL.Text),
    'rewardTier' : RewardTier,
    'assetHash' : IDL.Text,
    'membershipId' : IDL.Opt(IDL.Text),
    'nftUniqueId' : IDL.Text,
    'canisterId' : IDL.Text,
  });
  const Result_1 = IDL.Variant({
    'ok' : IDL.Vec(VerifyResult),
    'err' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : VerifyResult, 'err' : IDL.Text });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__adminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    '__collectionStore' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Collection))],
        ['query'],
      ),
    '__creatorIndex' : IDL.Func([], [IDL.Reserved], ['query']),
    '__globalAuditLog' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(AuditEntry)],
        ['query'],
      ),
    '__lastMintTime' : IDL.Func([], [IDL.Reserved], ['query']),
    '__mintCount' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextCollectionId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextNftId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nftStore' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Nft))],
        ['query'],
      ),
    '__paymentProofStore' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Text, PaymentProof))],
        ['query'],
      ),
    '__rateLimitStore' : IDL.Func([], [IDL.Reserved], ['query']),
    '__selfCanisterId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__stripeConfigStore' : IDL.Func([], [IDL.Reserved], ['query']),
    '__userStore' : IDL.Func(
        [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    '__verifiedEmails' : IDL.Func([], [IDL.Reserved], ['query']),
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_6], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'approvePaymentProof' : IDL.Func([IDL.Text], [Result_3], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'burnNft' : IDL.Func([IDL.Nat], [Result_2], []),
    'createCheckoutSession' : IDL.Func(
        [
          IDL.Vec(IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Nat })),
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'createCollection' : IDL.Func([IDL.Text, IDL.Text], [Result_5], []),
    'deleteCollection' : IDL.Func([IDL.Nat], [], []),
    'deleteNft' : IDL.Func([IDL.Nat], [Result_2], []),
    'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getCallerProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCanisterId' : IDL.Func([], [IDL.Text], ['query']),
    'getCollection' : IDL.Func([IDL.Nat], [IDL.Opt(Collection)], ['query']),
    'getCollectionId' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
    'getCreditsStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'used' : IDL.Nat,
            'remaining' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getMyPaymentProofs' : IDL.Func([], [IDL.Vec(PaymentProof)], ['query']),
    'getNft' : IDL.Func([IDL.Nat], [IDL.Opt(Nft)], ['query']),
    'getSlotsStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'used' : IDL.Nat,
            'remaining' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'status' : IDL.Text })],
        [],
      ),
    'getStripeStatus' : IDL.Func(
        [],
        [IDL.Record({ 'mode' : IDL.Text, 'configured' : IDL.Bool })],
        ['query'],
      ),
    'getTotalMinted' : IDL.Func([], [IDL.Nat], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listMyActiveNfts' : IDL.Func([], [IDL.Vec(Nft)], ['query']),
    'listMyCollections' : IDL.Func(
        [],
        [IDL.Vec(CollectionWithCount)],
        ['query'],
      ),
    'listMyNfts' : IDL.Func([], [IDL.Vec(Nft)], ['query']),
    'listPaymentProofs' : IDL.Func([], [IDL.Vec(PaymentProof)], ['query']),
    'mintNft' : IDL.Func(
        [
          ExternalBlob,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Result_4],
        [],
      ),
    'rejectPaymentProof' : IDL.Func([IDL.Text, IDL.Text], [Result_3], []),
    'saveCallerProfile' : IDL.Func([UserProfile], [], []),
    'sendVerificationEmail' : IDL.Func([IDL.Text], [], []),
    'setEmail' : IDL.Func([IDL.Text], [], []),
    'setEmailAlerts' : IDL.Func([IDL.Vec(AlertType)], [], []),
    'setOisyWalletAddress' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setUserStripeProductId' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [Result_2],
        [],
      ),
    'submitPaymentProof' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result_3],
        [],
      ),
    'transferNft' : IDL.Func([IDL.Nat, IDL.Principal], [TransferResult], []),
    'updateBusinessMetadata' : IDL.Func(
        [IDL.Nat, UpdateMetadataRequest],
        [Result_2],
        [],
      ),
    'verifyNftByCreatorId' : IDL.Func([IDL.Text], [Result_1], ['query']),
    'verifyNftPublic' : IDL.Func([IDL.Text], [Result], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };