/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AlertType = { 'mint_confirmation' : null } |
  { 'draft_purge' : null } |
  { 'subscription_expiry' : null } |
  { 'transfer_window' : null };
export interface AuditEntry {
  'action' : string,
  'timestamp' : Timestamp,
  'details' : [] | [string],
  'caller' : Principal,
}
export interface Collection {
  'id' : bigint,
  'ownerId' : Principal,
  'name' : string,
  'createdAt' : Timestamp,
  'tier' : SubscriptionTier,
  'description' : string,
  'maxSize' : bigint,
}
export interface CollectionWithCount {
  'id' : bigint,
  'ownerId' : Principal,
  'name' : string,
  'createdAt' : Timestamp,
  'tier' : SubscriptionTier,
  'description' : string,
  'nftCount' : bigint,
  'maxSize' : bigint,
}
export type CreatorId = string;
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export interface Nft {
  'id' : bigint,
  'status' : NftStatus,
  'title' : string,
  'imageBlob' : ExternalBlob,
  'edition' : string,
  'collectionId' : [] | [bigint],
  'ownerId' : Principal,
  'discountCode' : [] | [string],
  'tags' : Array<string>,
  'creatorId' : CreatorId,
  'businessName' : [] | [string],
  'mintDate' : Timestamp,
  'description' : string,
  'website' : [] | [string],
  'auditHistory' : Array<AuditEntry>,
  'rewardTier' : RewardTier,
  'assetHash' : string,
  'membershipId' : [] | [string],
  'nftUniqueId' : string,
}
export type NftStatus = { 'deleted' : null } |
  { 'active' : null } |
  { 'burned' : null };
export interface PaymentProof {
  'id' : string,
  'status' : PaymentProofStatus,
  'principal' : Principal,
  'rejectionReason' : [] | [string],
  'submittedAt' : bigint,
  'reviewedAt' : [] | [bigint],
  'reviewedBy' : [] | [Principal],
  'txHash' : string,
  'tierRequested' : string,
  'networkType' : string,
}
export type PaymentProofStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Result = { 'ok' : VerifyResult } |
  { 'err' : string };
export type Result_1 = { 'ok' : Array<VerifyResult> } |
  { 'err' : string };
export type Result_2 = { 'ok' : null } |
  { 'err' : string };
export type Result_3 = { 'ok' : string } |
  { 'err' : string };
export type Result_4 = {
    'ok' : {
      'id' : bigint,
      'tokenId' : bigint,
      'collectionId' : [] | [bigint],
      'nftUniqueId' : string,
    }
  } |
  { 'err' : { 'message' : string } };
export type Result_5 = { 'ok' : bigint } |
  { 'err' : string };
export type Result_6 = { 'ok' : null } |
  { 'err' : Error };
export type RewardTier = { 'bronze' : null } |
  { 'gold' : null } |
  { 'none' : null } |
  { 'platinum' : null } |
  { 'silver' : null };
export type SubscriptionTier = { 'org' : null } |
  { 'pro' : null } |
  { 'creator' : null } |
  { 'admin' : null } |
  { 'free' : null };
export type Timestamp = bigint;
export interface TransferResult {
  'newOwnerPrincipal' : [] | [string],
  'error' : [] | [string],
  'success' : boolean,
}
export interface UpdateMetadataRequest {
  'discountCode' : [] | [string],
  'tags' : [] | [Array<string>],
  'businessName' : [] | [string],
  'website' : [] | [string],
  'rewardTier' : [] | [RewardTier],
  'membershipId' : [] | [string],
}
export interface UserProfile {
  'creditsTotal' : bigint,
  'oisyWalletAddress' : [] | [string],
  'emailAlerts' : Array<AlertType>,
  'maxSlots' : bigint,
  'createdAt' : Timestamp,
  'subscriptionTier' : SubscriptionTier,
  'creatorId' : CreatorId,
  'email' : [] | [string],
  'stripeProductId' : [] | [string],
  'activeSlots' : bigint,
  'creditsUsed' : bigint,
  'principalId' : Principal,
  'creditsResetAt' : Timestamp,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VerifyResult {
  'tokenId' : bigint,
  'edition' : string,
  'collectionId' : [] | [bigint],
  'owner' : Principal,
  'discountCode' : [] | [string],
  'tags' : Array<string>,
  'creatorId' : CreatorId,
  'businessName' : [] | [string],
  'network' : string,
  'mintDate' : Timestamp,
  'website' : [] | [string],
  'rewardTier' : RewardTier,
  'assetHash' : string,
  'membershipId' : [] | [string],
  'nftUniqueId' : string,
  'canisterId' : string,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__adminPrincipal' : ActorMethod<[], [] | [Principal]>,
  '__collectionStore' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<[bigint, Collection]>
  >,
  '__creatorIndex' : ActorMethod<[], any>,
  '__globalAuditLog' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<AuditEntry>
  >,
  '__lastMintTime' : ActorMethod<[], any>,
  '__mintCount' : ActorMethod<[], any>,
  '__nextCollectionId' : ActorMethod<[], any>,
  '__nextNftId' : ActorMethod<[], any>,
  '__nftStore' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<[bigint, Nft]>
  >,
  '__paymentProofStore' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, PaymentProof]>
  >,
  '__rateLimitStore' : ActorMethod<[], any>,
  '__selfCanisterId' : ActorMethod<[], any>,
  '__stripeConfigStore' : ActorMethod<[], any>,
  '__userStore' : ActorMethod<
    [[] | [Principal], [] | [bigint]],
    Array<[Principal, UserProfile]>
  >,
  '__verifiedEmails' : ActorMethod<[], any>,
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_6>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'approvePaymentProof' : ActorMethod<[string], Result_3>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'burnNft' : ActorMethod<[bigint], Result_2>,
  'createCheckoutSession' : ActorMethod<
    [Array<{ 'name' : string, 'price' : bigint }>, string, string],
    string
  >,
  'createCollection' : ActorMethod<[string, string], Result_5>,
  'deleteCollection' : ActorMethod<[bigint], undefined>,
  'deleteNft' : ActorMethod<[bigint], Result_2>,
  'getAdminPrincipal' : ActorMethod<[], [] | [Principal]>,
  'getCallerProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCanisterId' : ActorMethod<[], string>,
  'getCollection' : ActorMethod<[bigint], [] | [Collection]>,
  'getCollectionId' : ActorMethod<[], [] | [bigint]>,
  'getCreditsStatus' : ActorMethod<
    [],
    { 'total' : bigint, 'used' : bigint, 'remaining' : bigint }
  >,
  'getMyPaymentProofs' : ActorMethod<[], Array<PaymentProof>>,
  'getNft' : ActorMethod<[bigint], [] | [Nft]>,
  'getSlotsStatus' : ActorMethod<
    [],
    { 'total' : bigint, 'used' : bigint, 'remaining' : bigint }
  >,
  'getStripeSessionStatus' : ActorMethod<[string], { 'status' : string }>,
  'getStripeStatus' : ActorMethod<
    [],
    { 'mode' : string, 'configured' : boolean }
  >,
  'getTotalMinted' : ActorMethod<[], bigint>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listMyActiveNfts' : ActorMethod<[], Array<Nft>>,
  'listMyCollections' : ActorMethod<[], Array<CollectionWithCount>>,
  'listMyNfts' : ActorMethod<[], Array<Nft>>,
  'listPaymentProofs' : ActorMethod<[], Array<PaymentProof>>,
  'mintNft' : ActorMethod<
    [
      ExternalBlob,
      string,
      string,
      string,
      string,
      [] | [bigint],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    Result_4
  >,
  'rejectPaymentProof' : ActorMethod<[string, string], Result_3>,
  'saveCallerProfile' : ActorMethod<[UserProfile], undefined>,
  'sendVerificationEmail' : ActorMethod<[string], undefined>,
  'setEmail' : ActorMethod<[string], undefined>,
  'setEmailAlerts' : ActorMethod<[Array<AlertType>], undefined>,
  'setOisyWalletAddress' : ActorMethod<[string], undefined>,
  'setStripeConfiguration' : ActorMethod<[string, string], undefined>,
  'setUserStripeProductId' : ActorMethod<[Principal, string], Result_2>,
  'submitPaymentProof' : ActorMethod<[string, string, string], Result_3>,
  'transferNft' : ActorMethod<[bigint, Principal], TransferResult>,
  'updateBusinessMetadata' : ActorMethod<
    [bigint, UpdateMetadataRequest],
    Result_2
  >,
  'verifyNftByCreatorId' : ActorMethod<[string], Result_1>,
  'verifyNftPublic' : ActorMethod<[string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];