/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type Result_2 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface AuditEntry {
    action: string;
    timestamp: Timestamp;
    details?: string;
    caller: Principal;
}
export type Result_5 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export type Result_1 = {
    __kind__: "ok";
    ok: Array<VerifyResult>;
} | {
    __kind__: "err";
    err: string;
};
export interface CollectionWithCount {
    id: bigint;
    ownerId: Principal;
    name: string;
    createdAt: Timestamp;
    tier: SubscriptionTier;
    description: string;
    nftCount: bigint;
    maxSize: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Result_4 = {
    __kind__: "ok";
    ok: {
        id: bigint;
        tokenId: bigint;
        collectionId?: bigint;
        nftUniqueId: string;
    };
} | {
    __kind__: "err";
    err: {
        message: string;
    };
};
export interface PaymentProof {
    id: string;
    status: PaymentProofStatus;
    principal: Principal;
    rejectionReason?: string;
    submittedAt: bigint;
    reviewedAt?: bigint;
    reviewedBy?: Principal;
    txHash: string;
    tierRequested: string;
    networkType: string;
}
export interface Nft {
    id: bigint;
    status: NftStatus;
    title: string;
    imageBlob: ExternalBlob;
    edition: string;
    collectionId?: bigint;
    ownerId: Principal;
    discountCode?: string;
    tags: Array<string>;
    creatorId: CreatorId;
    businessName?: string;
    mintDate: Timestamp;
    description: string;
    website?: string;
    auditHistory: Array<AuditEntry>;
    rewardTier: RewardTier;
    assetHash: string;
    membershipId?: string;
    nftUniqueId: string;
}
export interface UpdateMetadataRequest {
    discountCode?: string;
    tags?: Array<string>;
    businessName?: string;
    website?: string;
    rewardTier?: RewardTier;
    membershipId?: string;
}
export interface TransferResult {
    newOwnerPrincipal?: string;
    error?: string;
    success: boolean;
}
export interface VerifyResult {
    tokenId: bigint;
    edition: string;
    collectionId?: bigint;
    owner: Principal;
    discountCode?: string;
    tags: Array<string>;
    creatorId: CreatorId;
    businessName?: string;
    network: string;
    mintDate: Timestamp;
    website?: string;
    rewardTier: RewardTier;
    assetHash: string;
    membershipId?: string;
    nftUniqueId: string;
    canisterId: string;
}
export type Result_6 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export type CreatorId = string;
export type Result = {
    __kind__: "ok";
    ok: VerifyResult;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface Collection {
    id: bigint;
    ownerId: Principal;
    name: string;
    createdAt: Timestamp;
    tier: SubscriptionTier;
    description: string;
    maxSize: bigint;
}
export interface UserProfile {
    creditsTotal: bigint;
    oisyWalletAddress?: string;
    emailAlerts: Array<AlertType>;
    maxSlots: bigint;
    createdAt: Timestamp;
    subscriptionTier: SubscriptionTier;
    creatorId: CreatorId;
    email?: string;
    stripeProductId?: string;
    activeSlots: bigint;
    creditsUsed: bigint;
    principalId: Principal;
    creditsResetAt: Timestamp;
}
export enum AlertType {
    mint_confirmation = "mint_confirmation",
    draft_purge = "draft_purge",
    subscription_expiry = "subscription_expiry",
    transfer_window = "transfer_window"
}
export enum NftStatus {
    deleted = "deleted",
    active = "active",
    burned = "burned"
}
export enum PaymentProofStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum RewardTier {
    bronze = "bronze",
    gold = "gold",
    none = "none",
    platinum = "platinum",
    silver = "silver"
}
export enum SubscriptionTier {
    org = "org",
    pro = "pro",
    creator = "creator",
    admin = "admin",
    free = "free"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    __accessControlState(): Promise<any>;
    __adminPrincipal(): Promise<Principal | null>;
    __collectionStore(ko: bigint | null, count: bigint | null): Promise<Array<[bigint, Collection]>>;
    __creatorIndex(): Promise<any>;
    __globalAuditLog(io: bigint | null, count: bigint | null): Promise<Array<AuditEntry>>;
    __lastMintTime(): Promise<any>;
    __mintCount(): Promise<any>;
    __nextCollectionId(): Promise<any>;
    __nextNftId(): Promise<any>;
    __nftStore(ko: bigint | null, count: bigint | null): Promise<Array<[bigint, Nft]>>;
    __paymentProofStore(ko: string | null, count: bigint | null): Promise<Array<[string, PaymentProof]>>;
    __rateLimitStore(): Promise<any>;
    __selfCanisterId(): Promise<any>;
    __stripeConfigStore(): Promise<any>;
    __userStore(ko: Principal | null, count: bigint | null): Promise<Array<[Principal, UserProfile]>>;
    __verifiedEmails(): Promise<any>;
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result_6>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    approvePaymentProof(proofId: string): Promise<Result_3>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    burnNft(id: bigint): Promise<Result_2>;
    createCheckoutSession(_items: Array<{
        name: string;
        price: bigint;
    }>, _successUrl: string, _cancelUrl: string): Promise<string>;
    createCollection(name: string, description: string): Promise<Result_5>;
    deleteCollection(id: bigint): Promise<void>;
    deleteNft(id: bigint): Promise<Result_2>;
    getAdminPrincipal(): Promise<Principal | null>;
    getCallerProfile(): Promise<UserProfile>;
    getCallerUserRole(): Promise<UserRole>;
    getCanisterId(): Promise<string>;
    getCollection(id: bigint): Promise<Collection | null>;
    getCollectionId(): Promise<bigint | null>;
    getCreditsStatus(): Promise<{
        total: bigint;
        used: bigint;
        remaining: bigint;
    }>;
    getMyPaymentProofs(): Promise<Array<PaymentProof>>;
    getNft(id: bigint): Promise<Nft | null>;
    getSlotsStatus(): Promise<{
        total: bigint;
        used: bigint;
        remaining: bigint;
    }>;
    getStripeSessionStatus(_sessionId: string): Promise<{
        status: string;
    }>;
    getStripeStatus(): Promise<{
        mode: string;
        configured: boolean;
    }>;
    getTotalMinted(): Promise<bigint>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listMyActiveNfts(): Promise<Array<Nft>>;
    listMyCollections(): Promise<Array<CollectionWithCount>>;
    listMyNfts(): Promise<Array<Nft>>;
    listPaymentProofs(): Promise<Array<PaymentProof>>;
    mintNft(imageBlob: ExternalBlob, assetHash: string, title: string, description: string, edition: string, collectionId: bigint | null, businessName: string | null, website: string | null, discountCode: string | null, membershipId: string | null): Promise<Result_4>;
    rejectPaymentProof(proofId: string, reason: string): Promise<Result_3>;
    saveCallerProfile(profile: UserProfile): Promise<void>;
    sendVerificationEmail(email: string): Promise<void>;
    setEmail(email: string): Promise<void>;
    setEmailAlerts(alerts: Array<AlertType>): Promise<void>;
    setOisyWalletAddress(address: string): Promise<void>;
    setStripeConfiguration(secretKey: string, publicKey: string): Promise<void>;
    setUserStripeProductId(userPrincipal: Principal, productId: string): Promise<Result_2>;
    submitPaymentProof(txHash: string, tierRequested: string, networkType: string): Promise<Result_3>;
    transferNft(id: bigint, toPrincipal: Principal): Promise<TransferResult>;
    updateBusinessMetadata(id: bigint, updates: UpdateMetadataRequest): Promise<Result_2>;
    verifyNftByCreatorId(creatorId: string): Promise<Result_1>;
    verifyNftPublic(nftUniqueId: string): Promise<Result>;
}
import type { AlertType as _AlertType, AuditEntry as _AuditEntry, Collection as _Collection, CollectionWithCount as _CollectionWithCount, CreatorId as _CreatorId, Error as _Error, ExternalBlob as _ExternalBlob, Nft as _Nft, NftStatus as _NftStatus, PaymentProof as _PaymentProof, PaymentProofStatus as _PaymentProofStatus, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, RewardTier as _RewardTier, SubscriptionTier as _SubscriptionTier, Timestamp as _Timestamp, TransferResult as _TransferResult, UpdateMetadataRequest as _UpdateMetadataRequest, UserProfile as _UserProfile, UserRole as _UserRole, VerifyResult as _VerifyResult, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __accessControlState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__accessControlState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__accessControlState();
            return result;
        }
    }
    async __adminPrincipal(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.__adminPrincipal();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__adminPrincipal();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async __collectionStore(arg0: bigint | null, arg1: bigint | null): Promise<Array<[bigint, Collection]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__collectionStore(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__collectionStore(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async __creatorIndex(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__creatorIndex();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__creatorIndex();
            return result;
        }
    }
    async __globalAuditLog(arg0: bigint | null, arg1: bigint | null): Promise<Array<AuditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.__globalAuditLog(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__globalAuditLog(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async __lastMintTime(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__lastMintTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__lastMintTime();
            return result;
        }
    }
    async __mintCount(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__mintCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__mintCount();
            return result;
        }
    }
    async __nextCollectionId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextCollectionId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextCollectionId();
            return result;
        }
    }
    async __nextNftId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextNftId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextNftId();
            return result;
        }
    }
    async __nftStore(arg0: bigint | null, arg1: bigint | null): Promise<Array<[bigint, Nft]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__nftStore(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nftStore(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async __paymentProofStore(arg0: string | null, arg1: bigint | null): Promise<Array<[string, PaymentProof]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__paymentProofStore(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__paymentProofStore(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async __rateLimitStore(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__rateLimitStore();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__rateLimitStore();
            return result;
        }
    }
    async __selfCanisterId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__selfCanisterId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__selfCanisterId();
            return result;
        }
    }
    async __stripeConfigStore(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__stripeConfigStore();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__stripeConfigStore();
            return result;
        }
    }
    async __userStore(arg0: Principal | null, arg1: bigint | null): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__userStore(to_candid_opt_n31(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__userStore(to_candid_opt_n31(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async __verifiedEmails(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__verifiedEmails();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__verifiedEmails();
            return result;
        }
    }
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n39(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n39(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_6_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_6_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async approvePaymentProof(arg0: string): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.approvePaymentProof(arg0);
                return from_candid_Result_3_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approvePaymentProof(arg0);
            return from_candid_Result_3_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n51(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n51(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async burnNft(arg0: bigint): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.burnNft(arg0);
                return from_candid_Result_2_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.burnNft(arg0);
            return from_candid_Result_2_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCheckoutSession(arg0: Array<{
        name: string;
        price: bigint;
    }>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createCollection(arg0: string, arg1: string): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.createCollection(arg0, arg1);
                return from_candid_Result_5_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCollection(arg0, arg1);
            return from_candid_Result_5_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCollection(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCollection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCollection(arg0);
            return result;
        }
    }
    async deleteNft(arg0: bigint): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNft(arg0);
                return from_candid_Result_2_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNft(arg0);
            return from_candid_Result_2_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminPrincipal(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPrincipal();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPrincipal();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerProfile();
                return from_candid_UserProfile_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerProfile();
            return from_candid_UserProfile_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCanisterId(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCanisterId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCanisterId();
            return result;
        }
    }
    async getCollection(arg0: bigint): Promise<Collection | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollection(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollection(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollectionId(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollectionId();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollectionId();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCreditsStatus(): Promise<{
        total: bigint;
        used: bigint;
        remaining: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreditsStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreditsStatus();
            return result;
        }
    }
    async getMyPaymentProofs(): Promise<Array<PaymentProof>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPaymentProofs();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPaymentProofs();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNft(arg0: bigint): Promise<Nft | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNft(arg0);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNft(arg0);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSlotsStatus(): Promise<{
        total: bigint;
        used: bigint;
        remaining: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSlotsStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSlotsStatus();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<{
        status: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return result;
        }
    }
    async getStripeStatus(): Promise<{
        mode: string;
        configured: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeStatus();
            return result;
        }
    }
    async getTotalMinted(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalMinted();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalMinted();
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listMyActiveNfts(): Promise<Array<Nft>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyActiveNfts();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyActiveNfts();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyCollections(): Promise<Array<CollectionWithCount>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyCollections();
                return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyCollections();
            return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyNfts(): Promise<Array<Nft>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyNfts();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyNfts();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPaymentProofs(): Promise<Array<PaymentProof>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPaymentProofs();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPaymentProofs();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async mintNft(arg0: ExternalBlob, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint | null, arg6: string | null, arg7: string | null, arg8: string | null, arg9: string | null): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.mintNft(await to_candid_ExternalBlob_n66(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg9));
                return from_candid_Result_4_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mintNft(await to_candid_ExternalBlob_n66(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg9));
            return from_candid_Result_4_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectPaymentProof(arg0: string, arg1: string): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectPaymentProof(arg0, arg1);
                return from_candid_Result_3_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectPaymentProof(arg0, arg1);
            return from_candid_Result_3_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerProfile(to_candid_UserProfile_n70(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerProfile(to_candid_UserProfile_n70(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendVerificationEmail(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendVerificationEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendVerificationEmail(arg0);
            return result;
        }
    }
    async setEmail(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setEmail(arg0);
            return result;
        }
    }
    async setEmailAlerts(arg0: Array<AlertType>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setEmailAlerts(to_candid_vec_n72(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setEmailAlerts(to_candid_vec_n72(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setOisyWalletAddress(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOisyWalletAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOisyWalletAddress(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0, arg1);
            return result;
        }
    }
    async setUserStripeProductId(arg0: Principal, arg1: string): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserStripeProductId(arg0, arg1);
                return from_candid_Result_2_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserStripeProductId(arg0, arg1);
            return from_candid_Result_2_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitPaymentProof(arg0: string, arg1: string, arg2: string): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPaymentProof(arg0, arg1, arg2);
                return from_candid_Result_3_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPaymentProof(arg0, arg1, arg2);
            return from_candid_Result_3_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async transferNft(arg0: bigint, arg1: Principal): Promise<TransferResult> {
        if (this.processError) {
            try {
                const result = await this.actor.transferNft(arg0, arg1);
                return from_candid_TransferResult_n77(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferNft(arg0, arg1);
            return from_candid_TransferResult_n77(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBusinessMetadata(arg0: bigint, arg1: UpdateMetadataRequest): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBusinessMetadata(arg0, to_candid_UpdateMetadataRequest_n79(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_2_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBusinessMetadata(arg0, to_candid_UpdateMetadataRequest_n79(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_2_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyNftByCreatorId(arg0: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyNftByCreatorId(arg0);
                return from_candid_Result_1_n83(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyNftByCreatorId(arg0);
            return from_candid_Result_1_n83(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyNftPublic(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyNftPublic(arg0);
                return from_candid_Result_n88(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyNftPublic(arg0);
            return from_candid_Result_n88(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AlertType_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertType): AlertType {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_AuditEntry_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditEntry): AuditEntry {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_CollectionWithCount_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CollectionWithCount): CollectionWithCount {
    return from_candid_record_n65(_uploadFile, _downloadFile, value);
}
function from_candid_Collection_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Collection): Collection {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_NftStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NftStatus): NftStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_Nft_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Nft): Promise<Nft> {
    return await from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentProofStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentProofStatus): PaymentProofStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentProof_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentProof): PaymentProof {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n84(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n68(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function from_candid_Result_6_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_6): Result_6 {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n89(_uploadFile, _downloadFile, value);
}
function from_candid_RewardTier_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RewardTier): RewardTier {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionTier_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionTier): SubscriptionTier {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_TransferResult_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransferResult): TransferResult {
    return from_candid_record_n78(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function from_candid_VerifyResult_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerifyResult): VerifyResult {
    return from_candid_record_n87(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Collection]): Collection | null {
    return value.length === 0 ? null : from_candid_Collection_n5(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Nft]): Promise<Nft | null> {
    return value.length === 0 ? null : await from_candid_Nft_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    action: string;
    timestamp: _Timestamp;
    details: [] | [string];
    caller: Principal;
}): {
    action: string;
    timestamp: Timestamp;
    details?: string;
    caller: Principal;
} {
    return {
        action: value.action,
        timestamp: value.timestamp,
        details: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.details)),
        caller: value.caller
    };
}
async function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _NftStatus;
    title: string;
    imageBlob: _ExternalBlob;
    edition: string;
    collectionId: [] | [bigint];
    ownerId: Principal;
    discountCode: [] | [string];
    tags: Array<string>;
    creatorId: _CreatorId;
    businessName: [] | [string];
    mintDate: _Timestamp;
    description: string;
    website: [] | [string];
    auditHistory: Array<_AuditEntry>;
    rewardTier: _RewardTier;
    assetHash: string;
    membershipId: [] | [string];
    nftUniqueId: string;
}): Promise<{
    id: bigint;
    status: NftStatus;
    title: string;
    imageBlob: ExternalBlob;
    edition: string;
    collectionId?: bigint;
    ownerId: Principal;
    discountCode?: string;
    tags: Array<string>;
    creatorId: CreatorId;
    businessName?: string;
    mintDate: Timestamp;
    description: string;
    website?: string;
    auditHistory: Array<AuditEntry>;
    rewardTier: RewardTier;
    assetHash: string;
    membershipId?: string;
    nftUniqueId: string;
}> {
    return {
        id: value.id,
        status: from_candid_NftStatus_n17(_uploadFile, _downloadFile, value.status),
        title: value.title,
        imageBlob: await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.imageBlob),
        edition: value.edition,
        collectionId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.collectionId)),
        ownerId: value.ownerId,
        discountCode: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.discountCode)),
        tags: value.tags,
        creatorId: value.creatorId,
        businessName: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.businessName)),
        mintDate: value.mintDate,
        description: value.description,
        website: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.website)),
        auditHistory: from_candid_vec_n9(_uploadFile, _downloadFile, value.auditHistory),
        rewardTier: from_candid_RewardTier_n21(_uploadFile, _downloadFile, value.rewardTier),
        assetHash: value.assetHash,
        membershipId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.membershipId)),
        nftUniqueId: value.nftUniqueId
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _PaymentProofStatus;
    principal: Principal;
    rejectionReason: [] | [string];
    submittedAt: bigint;
    reviewedAt: [] | [bigint];
    reviewedBy: [] | [Principal];
    txHash: string;
    tierRequested: string;
    networkType: string;
}): {
    id: string;
    status: PaymentProofStatus;
    principal: Principal;
    rejectionReason?: string;
    submittedAt: bigint;
    reviewedAt?: bigint;
    reviewedBy?: Principal;
    txHash: string;
    tierRequested: string;
    networkType: string;
} {
    return {
        id: value.id,
        status: from_candid_PaymentProofStatus_n28(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        rejectionReason: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.rejectionReason)),
        submittedAt: value.submittedAt,
        reviewedAt: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.reviewedAt)),
        reviewedBy: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.reviewedBy)),
        txHash: value.txHash,
        tierRequested: value.tierRequested,
        networkType: value.networkType
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    creditsTotal: bigint;
    oisyWalletAddress: [] | [string];
    emailAlerts: Array<_AlertType>;
    maxSlots: bigint;
    createdAt: _Timestamp;
    subscriptionTier: _SubscriptionTier;
    creatorId: _CreatorId;
    email: [] | [string];
    stripeProductId: [] | [string];
    activeSlots: bigint;
    creditsUsed: bigint;
    principalId: Principal;
    creditsResetAt: _Timestamp;
}): {
    creditsTotal: bigint;
    oisyWalletAddress?: string;
    emailAlerts: Array<AlertType>;
    maxSlots: bigint;
    createdAt: Timestamp;
    subscriptionTier: SubscriptionTier;
    creatorId: CreatorId;
    email?: string;
    stripeProductId?: string;
    activeSlots: bigint;
    creditsUsed: bigint;
    principalId: Principal;
    creditsResetAt: Timestamp;
} {
    return {
        creditsTotal: value.creditsTotal,
        oisyWalletAddress: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.oisyWalletAddress)),
        emailAlerts: from_candid_vec_n36(_uploadFile, _downloadFile, value.emailAlerts),
        maxSlots: value.maxSlots,
        createdAt: value.createdAt,
        subscriptionTier: from_candid_SubscriptionTier_n7(_uploadFile, _downloadFile, value.subscriptionTier),
        creatorId: value.creatorId,
        email: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.email)),
        stripeProductId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.stripeProductId)),
        activeSlots: value.activeSlots,
        creditsUsed: value.creditsUsed,
        principalId: value.principalId,
        creditsResetAt: value.creditsResetAt
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    ownerId: Principal;
    name: string;
    createdAt: _Timestamp;
    tier: _SubscriptionTier;
    description: string;
    maxSize: bigint;
}): {
    id: bigint;
    ownerId: Principal;
    name: string;
    createdAt: Timestamp;
    tier: SubscriptionTier;
    description: string;
    maxSize: bigint;
} {
    return {
        id: value.id,
        ownerId: value.ownerId,
        name: value.name,
        createdAt: value.createdAt,
        tier: from_candid_SubscriptionTier_n7(_uploadFile, _downloadFile, value.tier),
        description: value.description,
        maxSize: value.maxSize
    };
}
function from_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    ownerId: Principal;
    name: string;
    createdAt: _Timestamp;
    tier: _SubscriptionTier;
    description: string;
    nftCount: bigint;
    maxSize: bigint;
}): {
    id: bigint;
    ownerId: Principal;
    name: string;
    createdAt: Timestamp;
    tier: SubscriptionTier;
    description: string;
    nftCount: bigint;
    maxSize: bigint;
} {
    return {
        id: value.id,
        ownerId: value.ownerId,
        name: value.name,
        createdAt: value.createdAt,
        tier: from_candid_SubscriptionTier_n7(_uploadFile, _downloadFile, value.tier),
        description: value.description,
        nftCount: value.nftCount,
        maxSize: value.maxSize
    };
}
function from_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    tokenId: bigint;
    collectionId: [] | [bigint];
    nftUniqueId: string;
}): {
    id: bigint;
    tokenId: bigint;
    collectionId?: bigint;
    nftUniqueId: string;
} {
    return {
        id: value.id,
        tokenId: value.tokenId,
        collectionId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.collectionId)),
        nftUniqueId: value.nftUniqueId
    };
}
function from_candid_record_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    newOwnerPrincipal: [] | [string];
    error: [] | [string];
    success: boolean;
}): {
    newOwnerPrincipal?: string;
    error?: string;
    success: boolean;
} {
    return {
        newOwnerPrincipal: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.newOwnerPrincipal)),
        error: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.error)),
        success: value.success
    };
}
function from_candid_record_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tokenId: bigint;
    edition: string;
    collectionId: [] | [bigint];
    owner: Principal;
    discountCode: [] | [string];
    tags: Array<string>;
    creatorId: _CreatorId;
    businessName: [] | [string];
    network: string;
    mintDate: _Timestamp;
    website: [] | [string];
    rewardTier: _RewardTier;
    assetHash: string;
    membershipId: [] | [string];
    nftUniqueId: string;
    canisterId: string;
}): {
    tokenId: bigint;
    edition: string;
    collectionId?: bigint;
    owner: Principal;
    discountCode?: string;
    tags: Array<string>;
    creatorId: CreatorId;
    businessName?: string;
    network: string;
    mintDate: Timestamp;
    website?: string;
    rewardTier: RewardTier;
    assetHash: string;
    membershipId?: string;
    nftUniqueId: string;
    canisterId: string;
} {
    return {
        tokenId: value.tokenId,
        edition: value.edition,
        collectionId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.collectionId)),
        owner: value.owner,
        discountCode: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.discountCode)),
        tags: value.tags,
        creatorId: value.creatorId,
        businessName: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.businessName)),
        network: value.network,
        mintDate: value.mintDate,
        website: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.website)),
        rewardTier: from_candid_RewardTier_n21(_uploadFile, _downloadFile, value.rewardTier),
        assetHash: value.assetHash,
        membershipId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.membershipId)),
        nftUniqueId: value.nftUniqueId,
        canisterId: value.canisterId
    };
}
async function from_candid_tuple_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _Nft]): Promise<[bigint, Nft]> {
    return [
        value[0],
        await from_candid_Nft_n15(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _PaymentProof]): [string, PaymentProof] {
    return [
        value[0],
        from_candid_PaymentProof_n26(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n34(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _Collection]): [bigint, Collection] {
    return [
        value[0],
        from_candid_Collection_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deleted: null;
} | {
    active: null;
} | {
    burned: null;
}): NftStatus {
    return "deleted" in value ? NftStatus.deleted : "active" in value ? NftStatus.active : "burned" in value ? NftStatus.burned : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bronze: null;
} | {
    gold: null;
} | {
    none: null;
} | {
    platinum: null;
} | {
    silver: null;
}): RewardTier {
    return "bronze" in value ? RewardTier.bronze : "gold" in value ? RewardTier.gold : "none" in value ? RewardTier.none : "platinum" in value ? RewardTier.platinum : "silver" in value ? RewardTier.silver : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): PaymentProofStatus {
    return "pending" in value ? PaymentProofStatus.pending : "approved" in value ? PaymentProofStatus.approved : "rejected" in value ? PaymentProofStatus.rejected : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mint_confirmation: null;
} | {
    draft_purge: null;
} | {
    subscription_expiry: null;
} | {
    transfer_window: null;
}): AlertType {
    return "mint_confirmation" in value ? AlertType.mint_confirmation : "draft_purge" in value ? AlertType.draft_purge : "subscription_expiry" in value ? AlertType.subscription_expiry : "transfer_window" in value ? AlertType.transfer_window : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n47(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        id: bigint;
        tokenId: bigint;
        collectionId: [] | [bigint];
        nftUniqueId: string;
    };
} | {
    err: {
        message: string;
    };
}): {
    __kind__: "ok";
    ok: {
        id: bigint;
        tokenId: bigint;
        collectionId?: bigint;
        nftUniqueId: string;
    };
} | {
    __kind__: "err";
    err: {
        message: string;
    };
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_record_n69(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    org: null;
} | {
    pro: null;
} | {
    creator: null;
} | {
    admin: null;
} | {
    free: null;
}): SubscriptionTier {
    return "org" in value ? SubscriptionTier.org : "pro" in value ? SubscriptionTier.pro : "creator" in value ? SubscriptionTier.creator : "admin" in value ? SubscriptionTier.admin : "free" in value ? SubscriptionTier.free : value;
}
function from_candid_variant_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_VerifyResult>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<VerifyResult>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n85(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _VerifyResult;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: VerifyResult;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_VerifyResult_n86(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
async function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _Nft]>): Promise<Array<[bigint, Nft]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n14(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _PaymentProof]>): Array<[string, PaymentProof]> {
    return value.map((x)=>from_candid_tuple_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _Collection]>): Array<[bigint, Collection]> {
    return value.map((x)=>from_candid_tuple_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AlertType>): Array<AlertType> {
    return value.map((x)=>from_candid_AlertType_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentProof>): Array<PaymentProof> {
    return value.map((x)=>from_candid_PaymentProof_n26(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Nft>): Promise<Array<Nft>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Nft_n15(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CollectionWithCount>): Array<CollectionWithCount> {
    return value.map((x)=>from_candid_CollectionWithCount_n64(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VerifyResult>): Array<VerifyResult> {
    return value.map((x)=>from_candid_VerifyResult_n86(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AuditEntry>): Array<AuditEntry> {
    return value.map((x)=>from_candid_AuditEntry_n10(_uploadFile, _downloadFile, x));
}
function to_candid_AlertType_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertType): _AlertType {
    return to_candid_variant_n74(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_RewardTier_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RewardTier): _RewardTier {
    return to_candid_variant_n82(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionTier_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): _SubscriptionTier {
    return to_candid_variant_n76(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateMetadataRequest_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateMetadataRequest): _UpdateMetadataRequest {
    return to_candid_record_n80(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n71(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n40(_uploadFile, _downloadFile, value));
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    creditsTotal: bigint;
    oisyWalletAddress?: string;
    emailAlerts: Array<AlertType>;
    maxSlots: bigint;
    createdAt: Timestamp;
    subscriptionTier: SubscriptionTier;
    creatorId: CreatorId;
    email?: string;
    stripeProductId?: string;
    activeSlots: bigint;
    creditsUsed: bigint;
    principalId: Principal;
    creditsResetAt: Timestamp;
}): {
    creditsTotal: bigint;
    oisyWalletAddress: [] | [string];
    emailAlerts: Array<_AlertType>;
    maxSlots: bigint;
    createdAt: _Timestamp;
    subscriptionTier: _SubscriptionTier;
    creatorId: _CreatorId;
    email: [] | [string];
    stripeProductId: [] | [string];
    activeSlots: bigint;
    creditsUsed: bigint;
    principalId: Principal;
    creditsResetAt: _Timestamp;
} {
    return {
        creditsTotal: value.creditsTotal,
        oisyWalletAddress: value.oisyWalletAddress ? candid_some(value.oisyWalletAddress) : candid_none(),
        emailAlerts: to_candid_vec_n72(_uploadFile, _downloadFile, value.emailAlerts),
        maxSlots: value.maxSlots,
        createdAt: value.createdAt,
        subscriptionTier: to_candid_SubscriptionTier_n75(_uploadFile, _downloadFile, value.subscriptionTier),
        creatorId: value.creatorId,
        email: value.email ? candid_some(value.email) : candid_none(),
        stripeProductId: value.stripeProductId ? candid_some(value.stripeProductId) : candid_none(),
        activeSlots: value.activeSlots,
        creditsUsed: value.creditsUsed,
        principalId: value.principalId,
        creditsResetAt: value.creditsResetAt
    };
}
function to_candid_record_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    discountCode?: string;
    tags?: Array<string>;
    businessName?: string;
    website?: string;
    rewardTier?: RewardTier;
    membershipId?: string;
}): {
    discountCode: [] | [string];
    tags: [] | [Array<string>];
    businessName: [] | [string];
    website: [] | [string];
    rewardTier: [] | [_RewardTier];
    membershipId: [] | [string];
} {
    return {
        discountCode: value.discountCode ? candid_some(value.discountCode) : candid_none(),
        tags: value.tags ? candid_some(value.tags) : candid_none(),
        businessName: value.businessName ? candid_some(value.businessName) : candid_none(),
        website: value.website ? candid_some(value.website) : candid_none(),
        rewardTier: value.rewardTier ? candid_some(to_candid_RewardTier_n81(_uploadFile, _downloadFile, value.rewardTier)) : candid_none(),
        membershipId: value.membershipId ? candid_some(value.membershipId) : candid_none()
    };
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertType): {
    mint_confirmation: null;
} | {
    draft_purge: null;
} | {
    subscription_expiry: null;
} | {
    transfer_window: null;
} {
    return value == AlertType.mint_confirmation ? {
        mint_confirmation: null
    } : value == AlertType.draft_purge ? {
        draft_purge: null
    } : value == AlertType.subscription_expiry ? {
        subscription_expiry: null
    } : value == AlertType.transfer_window ? {
        transfer_window: null
    } : value;
}
function to_candid_variant_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): {
    org: null;
} | {
    pro: null;
} | {
    creator: null;
} | {
    admin: null;
} | {
    free: null;
} {
    return value == SubscriptionTier.org ? {
        org: null
    } : value == SubscriptionTier.pro ? {
        pro: null
    } : value == SubscriptionTier.creator ? {
        creator: null
    } : value == SubscriptionTier.admin ? {
        admin: null
    } : value == SubscriptionTier.free ? {
        free: null
    } : value;
}
function to_candid_variant_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RewardTier): {
    bronze: null;
} | {
    gold: null;
} | {
    none: null;
} | {
    platinum: null;
} | {
    silver: null;
} {
    return value == RewardTier.bronze ? {
        bronze: null
    } : value == RewardTier.gold ? {
        gold: null
    } : value == RewardTier.none ? {
        none: null
    } : value == RewardTier.platinum ? {
        platinum: null
    } : value == RewardTier.silver ? {
        silver: null
    } : value;
}
function to_candid_vec_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<AlertType>): Array<_AlertType> {
    return value.map((x)=>to_candid_AlertType_n73(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
